branches:
  only:
    - master

environment:
  nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

test_script:
  - npm test

# Don't actually build.
build: off
