name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install dependencies
      run: |
        npm ci
    - name: Verify code is formatted correctly
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write .
        dry: true
    - name: Run code coverage
      run: |
        npm run ci
        bash <(curl -s https://codecov.io/bash)
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        registry-url: https://blackbaud.pkgs.visualstudio.com/_packaging/Blackbaud-npm/npm/registry/
    - name: Install dependencies
      run: |
        npm i -g @angular/cli@11 @skyux-sdk/cli
        npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{secrets.BLACKBAUD_NPM_TOKEN}}
    - name: Install SKY UX certificate
      run: |
        skyux certs install
    - name: Create new Angular CLI application
      run: |
        ng new builders-e2e-app --legacy-browsers --routing --strict --style=scss
    - name: Build `@skyux-sdk/angular-builders`
      run: |
        node_modules/.bin/tsc -p tsconfig.json
        node ./scripts/after-build-success.js --test-app-directory builders-e2e-app
    - name: Add `@skyux-sdk/angular-builders`
      working-directory: builders-e2e-app
      run: |
        ng add ./.skyux-sdk-angular-builders-dist
        rm -r node_modules/@skyux-sdk/angular-builders
        mv ../dist node_modules/@skyux-sdk/angular-builders
    - name: Run Angular CLI commands
      working-directory: builders-e2e-app
      run: |
        npm i --no-save --no-package-lock blackbaud/skyux-sdk-pipeline-settings
        ng version
        ng lint
        ng build --prod
        ng test --browsers=ChromeHeadless --watch=false --skyux-ci-platform=gh-actions
        ng e2e --skyux-ci-platform=gh-actions
