name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: Install and run tests
      run: |
        npm ci
        npm run ci
        bash <(curl -s https://codecov.io/bash)
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: Install and run e2e
      run: |
        npm ci
        npm run build
        cd builders-test-app
        npm ci
        npm run dev-setup
        npx -p @angular/cli@11 ng lint
        npx -p @angular/cli@11 ng build --prod
        npx -p @angular/cli@11 ng test --browsers="ChromeHeadless" --no-watch
        npx -p @angular/cli@11 ng e2e
