name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    steps:
    - name: Install and run tests
      run: |
        npm ci
        npm run ci
        bash <(curl -s https://codecov.io/bash)
