name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install and run tests
      run: |
        npm ci
        npm run ci
        bash <(curl -s https://codecov.io/bash)
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install and run e2e
      run: |
        npm i -g @angular/cli@11
        ng new builders-e2e-app --legacy-browsers --routing --strict --style=scss
        npm ci
        node_modules/.bin/tsc -p tsconfig.json
        node ./scripts/after-build-success.js --test-dir builders-e2e-app
        cd builders-e2e-app
        ng add ./.skyux-sdk-angular-builders-dist
        ng lint
        ng build --prod
        ng test --browsers=ChromeHeadless --code-coverage --watch=false
        ng e2e
