name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and run tests
      run: |
        npm ci
        npm run ci
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
